### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by AIPTU** [Sergittos/ChatCooldown#2]
I'm very happy if there is this feature in your plugin
- Check words and include ip, url
- Anti caps and include chat duplicate
- Auto mutes system
- Maximum message length

**Comment by JuqnDev** [comment]
> I'm very happy if there is this feature in your plugin
> 
> * Check words and include ip, url
> * Anti caps and include chat duplicate
> * Auto mutes system
> * Maximum message length

This plugin is not inspired by a "Chat Core". As its name says, it is a cooldown chat, so I consider that this should not go in this plugin.
